name: Deploy App
on:
  push:
    branches:
      - main
    paths:
      - "packages/common/**"
      - "packages/app/**"
      - "infra/app/**"
      - ".github/workflows/deploy-app.yaml"

jobs:
  deploy:
    name: deploy-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: touch ./packages/app/.env

      - run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env \
          && echo "DATABASE_AUTH_TOKEN=${{secrets.DATABASE_AUTH_TOKEN}}" >> .env \
          && echo "PUBLIC_WEBSITE_URL=${{secrets.PUBLIC_WEBSITE_URL}}" >> .env \
          && echo "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env \
          && echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env
        working-directory: ./packages/app

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --dockerfile ./infra/app/Dockerfile -c ./infra/app/fly.toml -a awful-todos
        env:
          FLY_API_TOKEN: ${{ secrets.APP_FLY_DEPLOY_TOKEN }}
